"""empty message

Revision ID: 4ed8e28a9ca5
Revises: 18d291a681b8
Create Date: 2020-09-24 23:42:59.277911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ed8e28a9ca5'
down_revision = '18d291a681b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeling')
    op.add_column('producto', sa.Column('etiqueta_dos', sa.Enum('ALIMENTOS','ALIMENTOS', 'BEBIDAS', 'SALSAS', 'REFRESCOS', 'JUGOS', name='etiqueta'), nullable=True))
    op.add_column('producto', sa.Column('etiqueta_tres', sa.Enum('ALIMENTOS', 'BEBIDAS', 'SALSAS', 'REFRESCOS', 'JUGOS', name='etiqueta'), nullable=True))
    op.add_column('producto', sa.Column('etiqueta_uno', sa.Enum('ALIMENTOS', 'BEBIDAS', 'SALSAS', 'REFRESCOS', 'JUGOS', name='etiqueta'), nullable=False))
    op.alter_column('producto', 'foto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto', 'foto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('producto', 'etiqueta_uno')
    op.drop_column('producto', 'etiqueta_tres')
    op.drop_column('producto', 'etiqueta_dos')
    op.create_table('feeling',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('as_felt_before', mysql.ENUM('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER'), nullable=False),
    sa.Column('as_felt_afterwards', mysql.ENUM('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
