"""empty message

Revision ID: 9be4e4d287f1
Revises: fd3c88e02b24
Create Date: 2020-09-22 14:33:01.091748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be4e4d287f1'
down_revision = 'fd3c88e02b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('foto_perfil', table_name='usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('foto_perfil', 'usuario', ['foto_perfil'], unique=True)
    # ### end Alembic commands ###
