"""empty message

Revision ID: cb775121cfb3
Revises: e84d40b2eee2
Create Date: 2020-09-24 21:25:15.603213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb775121cfb3'
down_revision = 'e84d40b2eee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_activity', sa.String(length=100), nullable=True),
    sa.Column('next_activity', sa.String(length=100), nullable=True),
    sa.Column('as_felt_before', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.Column('as_felt_afterwards', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeling')
    # ### end Alembic commands ###
