"""empty message

Revision ID: db3b9c395929
Revises: 4756f0b2f821
Create Date: 2020-09-25 18:51:47.245607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3b9c395929'
down_revision = '4756f0b2f821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('etiqueta_dos', sa.Enum('ALIMENTOS', 'BEBIDAS', 'SALSAS', 'ENLATADOS', 'REFRESCOS', 'JUGOS', 'CEREALES', name='etiqueta'), nullable=True))
    op.add_column('producto', sa.Column('etiqueta_tres', sa.Enum('ALIMENTOS', 'BEBIDAS', 'SALSAS', 'ENLATADOS', 'REFRESCOS', 'JUGOS', 'CEREALES', name='etiqueta'), nullable=True))
    op.add_column('producto', sa.Column('etiqueta_uno', sa.Enum('ALIMENTOS', 'BEBIDAS', 'SALSAS', 'ENLATADOS', 'REFRESCOS', 'JUGOS', 'CEREALES', name='etiqueta'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'etiqueta_uno')
    op.drop_column('producto', 'etiqueta_tres')
    op.drop_column('producto', 'etiqueta_dos')
    # ### end Alembic commands ###
