"""empty message

Revision ID: e84d40b2eee2
Revises: 3819b4d0b7ea
Create Date: 2020-09-24 18:43:39.979843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e84d40b2eee2'
down_revision = '3819b4d0b7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nombre', table_name='etiqueta')
    op.drop_table('etiqueta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre', 'etiqueta', ['nombre'], unique=True)
    # ### end Alembic commands ###
