"""empty message

Revision ID: fb4addd8b297
Revises: cb775121cfb3
Create Date: 2020-09-24 21:27:07.852346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb4addd8b297'
down_revision = 'cb775121cfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeling', 'previous_activity')
    op.drop_column('feeling', 'next_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeling', sa.Column('next_activity', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('feeling', sa.Column('previous_activity', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
